### PR TITLE
Use cmake-ninja to build libofx

### PR DESCRIPTION
**Pull request by travier**
https://github.com/flathub/flathub/pull/4337#issuecomment-1666629471

### CODE REVIEW

**Comment by travier** [comment]
bot, buld

**Comment by tsdgeos** [comment]
Why do we have to build a host of new dependencies now?

**Comment by travier** [comment]
It could be that the current build system did not figure out that they were missing. I haven't fully investigated yet.

**Comment by Justinzobel** [comment]
Ping?

**Comment by Justinzobel** [comment]
@travier you were so close, you just had the wrong libxml++ version.

**Comment by travier** [comment]
Thanks!

**Pull request merged**
